app:
  message: Message has been sent Successfully!
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: request.exchange       # ${} java
    queue: request.queue             #
    routingkey: request.routingkey   #
server:
  port: 9091